[project]
name = "fastnet-inference"
version = "0.1.0"
description = "Inference routines for the FastNet AI model for global weather prediction."
readme = "README.md"
authors = [
    { name = "UK Met Office", email = "" }
]
requires-python = ">=3.11"
dependencies = [
    "anemoi-datasets==0.5.28",
    "cartopy>=0.25.0",
    "pytest>=9.0.2",
    "torch>=2.6",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
