[project]
name = "fastnet-inference"
version = "0.1.0"
description = "Inference routines for the FastNet AI model for global weather prediction."
readme = "README.md"
authors = [
    { name = "UK Met Office", email = "" }
]
requires-python = ">=3.11"
dependencies = [
    "anemoi-datasets==0.5.28",
    "cartopy>=0.25.0",
    "huggingface-hub>=1.2.3",
    "pytest>=9.0.2",
    "rich>=14.2.0",
    "torch>=2.13.0",
    "typer>=0.21.1",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"

[tool.pytest.ini_options]
testpaths = ["tests"]
addopts = ["-ra", "--showlocals", "--strict-markers", "--strict-config"]
xfail_strict = true
markers = [
    "requires_hf: marks tests that download the model from the Hugging Face Hub; skip in default CI, run in the hf-integration job.",
]

[dependency-groups]
dev = [
    "pre-commit>=4.5.1",
    "pytest>=9.0.2",
]

[project.scripts]
fastnet-inference = "fastnet_inference.cli:app"

[tool.ruff]
src = ["src"]
target-version = "py311"
line-length = 100
fix = true
show-fixes = true

[tool.ruff.lint]
extend-select = [
    "B",   # flake8-bugbear
    "I",   # isort
    "C4",  # flake8-comprehensions
    "EM",  # flake8-errmsg
    "ICN", # flake8-import-conventions
    "G",   # flake8-logging-format
    "PGH", # pygrep-hooks
    "PIE", # flake8-pie
    "PT",  # flake8-pytest-style
    "RET", # flake8-return
    "RUF", # Ruff-specific
    "SIM", # flake8-simplify
    "UP",  # pyupgrade
    "YTT", # flake8-2020
	"S",   # security
	"ARG",  # unused arguments
	"T20",  # no printing in library code (prefer the `logging` library)
	"TC",   # move imports that are type-checking only under `TYPE_CHECKING` block
]
ignore = [
    "ISC001", # Conflicts with formatter
    "B017",   # Duplicate (covered by PT011)
]

[tool.ruff.lint.per-file-ignores]
"tests/*" = ["S101"]

[tool.ruff.format]
preview = true
