[project]
name = "fastnet-inference"
version = "0.1.0"
description = "Inference routines for the FastNet AI model for global weather prediction."
readme = "README.md"
authors = [
    { name = "UK Met Office", email = "" }
]
requires-python = ">=3.11"
dependencies = [
    "anemoi-datasets>=0.5.28",
    "anemoi-training>=0.8.1",
    "jaxtyping>=0.3.3",
    "torch>=2.9.1",
]

[build-system]
requires = ["uv_build>=0.9.13,<0.10.0"]
build-backend = "uv_build"
