LONGHAND_VARIABLE_TO_ANEMOI_ERA5_SHORTHAND = {
    "10m_u_component_of_wind": "10u",
    "10m_v_component_of_wind": "10v",
    "2m_dewpoint_temperature": "2d",
    "2m_temperature": "2t",
    "convective_precipitation": "cp",
    "cos_latitude": "cos_latitude",
    "cos_longitude": "cos_longitude",
    "geopotential": "z",
    "land_sea_mask": "lsm",
    "mean_sea_level_pressure": "msl",
    "potential_vorticity": "pv",
    "relative_humidity": "r",
    "sin_latitude": "sin_latitude",
    "sin_longitude": "sin_longitude",
    "skin_temperature": "skt",
    "slope_of_sub_gridscale_orography": "slor",
    "snow_depth": "sd",
    "specific_humidity": "q",
    "standard_deviation_of_orography": "sdor",
    "surface_pressure": "sp",
    "temperature": "t",
    "toa_incident_solar_radiation": "insolation",
    "total_cloud_cover": "tcc",
    "total_column_water": "tcw",
    "total_precipitation": "tp",
    "u_component_of_wind": "u",
    "v_component_of_wind": "v",
    "vertical_velocity": "w",
    "vorticity": "vo",
    "sin_local_time": "sin_local_time",
    "cos_local_time": "cos_local_time",
    "cos_julian_day": "cos_julian_day",
    "sin_julian_day": "sin_julian_day",
    "cos_lat": "cos_latitude",
    "cos_lon": "cos_longitude",
    "sin_lat": "sin_latitude",
    "sin_lon": "sin_longitude",
    "lsm": "lsm",
    "sdor": "sdor",
    "slor": "slor",
    "orography": "orography",
}

FORECAST_VARS_ORDER_FASTNET = (
    ("10m_u_component_of_wind", 0),
    ("10m_v_component_of_wind", 0),
    ("2m_dewpoint_temperature", 0),
    ("2m_temperature", 0),
    ("mean_sea_level_pressure", 0),
    ("skin_temperature", 0),
    ("surface_pressure", 0),
    ("geopotential", 50),
    ("geopotential", 100),
    ("geopotential", 150),
    ("geopotential", 200),
    ("geopotential", 250),
    ("geopotential", 300),
    ("geopotential", 400),
    ("geopotential", 500),
    ("geopotential", 600),
    ("geopotential", 700),
    ("geopotential", 850),
    ("geopotential", 925),
    ("geopotential", 1000),
    ("specific_humidity", 50),
    ("specific_humidity", 100),
    ("specific_humidity", 150),
    ("specific_humidity", 200),
    ("specific_humidity", 250),
    ("specific_humidity", 300),
    ("specific_humidity", 400),
    ("specific_humidity", 500),
    ("specific_humidity", 600),
    ("specific_humidity", 700),
    ("specific_humidity", 850),
    ("specific_humidity", 925),
    ("specific_humidity", 1000),
    ("temperature", 50),
    ("temperature", 100),
    ("temperature", 150),
    ("temperature", 200),
    ("temperature", 250),
    ("temperature", 300),
    ("temperature", 400),
    ("temperature", 500),
    ("temperature", 600),
    ("temperature", 700),
    ("temperature", 850),
    ("temperature", 925),
    ("temperature", 1000),
    ("u_component_of_wind", 50),
    ("u_component_of_wind", 100),
    ("u_component_of_wind", 150),
    ("u_component_of_wind", 200),
    ("u_component_of_wind", 250),
    ("u_component_of_wind", 300),
    ("u_component_of_wind", 400),
    ("u_component_of_wind", 500),
    ("u_component_of_wind", 600),
    ("u_component_of_wind", 700),
    ("u_component_of_wind", 850),
    ("u_component_of_wind", 925),
    ("u_component_of_wind", 1000),
    ("v_component_of_wind", 50),
    ("v_component_of_wind", 100),
    ("v_component_of_wind", 150),
    ("v_component_of_wind", 200),
    ("v_component_of_wind", 250),
    ("v_component_of_wind", 300),
    ("v_component_of_wind", 400),
    ("v_component_of_wind", 500),
    ("v_component_of_wind", 600),
    ("v_component_of_wind", 700),
    ("v_component_of_wind", 850),
    ("v_component_of_wind", 925),
    ("v_component_of_wind", 1000),
)

NONFORECAST_VARS_ORDER_FASTNET = (
    ("cos_lat", 0),
    ("cos_lon", 0),
    ("sin_lon", 0),
    ("lsm", 0),
    ("orography", 0),
    ("sdor", 0),
    ("slor", 0),
    ("cos_julian_day", 0),
    ("cos_local_time", 0),
    ("sin_julian_day", 0),
    ("sin_local_time", 0),
    ("toa_incident_solar_radiation", 0),
)

ERA5_VARIABLE_TO_STATS_SHORTHAND = {
    "10m_u_component_of_wind": "u10",
    "10m_v_component_of_wind": "v10",
    "2m_dewpoint_temperature": "2d",
    "2m_temperature": "t2m",
    "convective_precipitation": "cp",
    "cos_latitude": "cos_latitude",
    "cos_longitude": "cos_longitude",
    "geopotential": "z",
    "land_sea_mask": "lsm",
    "mean_sea_level_pressure": "msl",
    "potential_vorticity": "pv",
    "relative_humidity": "r",
    "sin_latitude": "sin_latitude",
    "sin_longitude": "sin_longitude",
    "skin_temperature": "skt",
    "slope_of_sub_gridscale_orography": "slor",
    "snow_depth": "sd",
    "specific_humidity": "q",
    "standard_deviation_of_orography": "sdor",
    "surface_pressure": "sp",
    "temperature": "t",
    "toa_incident_solar_radiation": "tisr",
    "total_cloud_cover": "tcc",
    "total_column_water": "tcw",
    "total_precipitation": "tp",
    "u_component_of_wind": "u",
    "v_component_of_wind": "v",
    "vertical_velocity": "w",
    "vorticity": "vo",
    "sin_local_time": "sin_local_time",
    "cos_local_time": "cos_local_time",
    "cos_julian_day": "cos_julian_day",
    "sin_julian_day": "sin_julian_day",
    "cos_lat": "cos_latitude",
    "cos_lon": "cos_longitude",
    "sin_lat": "sin_latitude",
    "sin_lon": "sin_longitude",
    "lsm": "lsm",
    "sdor": "sdor",
    "slor": "slor",
    "orography": "orography",
}


def get_anemoi_to_stats_mapping() -> dict[str, str]:
    """Build mapping from anemoi shorthand names to stats file names.

    Examples:
        mapping["10u"] -> "u10"
        mapping["z_500"] -> "z500"
        mapping["cos_julian_day"] -> "cos_julian_day"
    """
    mapping = {}

    for var, level in FORECAST_VARS_ORDER_FASTNET:
        anemoi_name = LONGHAND_VARIABLE_TO_ANEMOI_ERA5_SHORTHAND[var]
        stats_name = ERA5_VARIABLE_TO_STATS_SHORTHAND[var]
        if level != 0:
            anemoi_name += f"_{level}"  # e.g. z_500
            stats_name += str(level)     # e.g. z500
        mapping[anemoi_name] = stats_name

    for var, level in NONFORECAST_VARS_ORDER_FASTNET:
        anemoi_name = LONGHAND_VARIABLE_TO_ANEMOI_ERA5_SHORTHAND[var]
        stats_name = ERA5_VARIABLE_TO_STATS_SHORTHAND[var]
        if level != 0:
            anemoi_name += f"_{level}"
            stats_name += str(level)
        mapping[anemoi_name] = stats_name

    return mapping
